In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report,confusion_matrix
import pickle as pkl

In [2]:
# Reading the dataset
df = pd.read_csv(r"C:\Users\Mohan Patil\OneDrive\Desktop\Datasets\Churn (1).csv",index_col='Unnamed: 0')
df

,state,area.code,account.length,voice.plan,voice.messages,intl.plan,intl.mins,intl.calls,intl.charge,day.mins,day.calls,day.charge,eve.mins,eve.calls,eve.charge,night.mins,night.calls,night.charge,customer.calls,churn
1,KS,area_code_415,128,yes,25,no,10.0,3,2.70,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,1,no
2,OH,area_code_415,107,yes,26,no,13.7,3,3.70,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,1,no
3,NJ,area_code_415,137,no,0,no,12.2,5,3.29,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,0,no
4,OH,area_code_408,84,no,0,yes,6.6,7,1.78,299.4,71,50.9,61.9,88,5.26,196.9,89,8.86,2,no
5,OK,area_code_415,75,no,0,yes,10.1,3,2.73,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,3,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4996,HI,area_code_408,50,yes,40,no,9.9,5,2.67,235.7,127,40.07,223,126,18.96,297.5,116,13.39,2,no
4997,WV,area_code_415,152,no,0,no,14.7,2,3.97,184.2,90,31.31,256.8,73,21.83,213.6,113,9.61,3,yes
4998,DC,area_code_415,61,no,0,no,13.6,4,3.67,140.6,89,23.9,172.8,128,14.69,212.4,97,9.56,1,no
4999,DC,area_code_510,109,no,0,no,8.5,6,2.30,188.8,67,32.1,171.7,92,14.59,224.4,89,10.10,0,no
5000,VT,area_code_415,86,yes,34,no,9.3,16,2.51,129.4,102,22,267.1,104,22.70,154.8,100,6.97,0,no

In [3]:
df.drop(["area.code"],inplace=True,axis=1)
df.drop(["state"],inplace=True,axis=1)
df

,account.length,voice.plan,voice.messages,intl.plan,intl.mins,intl.calls,intl.charge,day.mins,day.calls,day.charge,eve.mins,eve.calls,eve.charge,night.mins,night.calls,night.charge,customer.calls,churn
1,128,yes,25,no,10.0,3,2.70,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,1,no
2,107,yes,26,no,13.7,3,3.70,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,1,no
3,137,no,0,no,12.2,5,3.29,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,0,no
4,84,no,0,yes,6.6,7,1.78,299.4,71,50.9,61.9,88,5.26,196.9,89,8.86,2,no
5,75,no,0,yes,10.1,3,2.73,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,3,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4996,50,yes,40,no,9.9,5,2.67,235.7,127,40.07,223,126,18.96,297.5,116,13.39,2,no
4997,152,no,0,no,14.7,2,3.97,184.2,90,31.31,256.8,73,21.83,213.6,113,9.61,3,yes
4998,61,no,0,no,13.6,4,3.67,140.6,89,23.9,172.8,128,14.69,212.4,97,9.56,1,no
4999,109,no,0,no,8.5,6,2.30,188.8,67,32.1,171.7,92,14.59,224.4,89,10.10,0,no
5000,86,yes,34,no,9.3,16,2.51,129.4,102,22,267.1,104,22.70,154.8,100,6.97,0,no

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5000 entries, 1 to 5000
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   account.length  5000 non-null   int64
 1   voice.plan      5000 non-null   object
 2   voice.messages  5000 non-null   int64
 3   intl.plan       5000 non-null   object
 4   intl.mins       5000 non-null   float64
 5   intl.calls      5000 non-null   int64
 6   intl.charge     5000 non-null   float64
 7   day.mins        5000 non-null   float64
 8   day.calls       5000 non-null   int64
 9   day.charge      5000 non-null   object
 10  eve.mins        5000 non-null   object
 11  eve.calls       5000 non-null   int64
 12  eve.charge      5000 non-null   float64
 13  night.mins      5000 non-null   float64
 14  night.calls     5000 non-null   int64
 15  night.charge    5000 non-null   float64
 16  customer.calls  5000 non-null   int64
 17  churn           5000 non-null   object
dtypes: float64(6), int64(7), object(5)
memory usage: 742.2+ KB

In [5]:
# Convert column to float beforing removing Nan value
column_convert = ['day.charge','eve.mins']
df[column_convert] = df[column_convert].astype(float)

In [6]:
non_numeric_value = pd.to_numeric(df['day.charge'],errors='coerce').isnull().sum()
print(non_numeric_value)

7

In [7]:
column_mean = pd.to_numeric(df['day.charge'],errors='coerce').mean()
df['day.charge'].fillna(column_mean,inplace=True) # Replacing the Nan Value with mean

In [8]:
non_numeric_value1 = pd.to_numeric(df['eve.mins'],errors='coerce').isnull().sum()
print(non_numeric_value1)

24

In [9]:
column_mean = pd.to_numeric(df['eve.mins'],errors='coerce').mean()
df['eve.mins'].fillna(column_mean,inplace=True) # Replacing the Nan Value with mean

In [10]:
df.head(15)

,account.length,voice.plan,voice.messages,intl.plan,intl.mins,intl.calls,intl.charge,day.mins,day.calls,day.charge,eve.mins,eve.calls,eve.charge,night.mins,night.calls,night.charge,customer.calls,churn
1,128,yes,25,no,10.0,3,2.70,265.1,110,45.070000,197.4,99,16.78,244.7,91,11.01,1,no
2,107,yes,26,no,13.7,3,3.70,161.6,123,27.470000,195.5,103,16.62,254.4,103,11.45,1,no
3,137,no,0,no,12.2,5,3.29,243.4,114,41.380000,121.2,110,10.30,162.6,104,7.32,0,no
4,84,no,0,yes,6.6,7,1.78,299.4,71,50.900000,61.9,88,5.26,196.9,89,8.86,2,no
5,75,no,0,yes,10.1,3,2.73,166.7,113,28.340000,148.3,122,12.61,186.9,121,8.41,3,no
6,118,no,0,yes,6.3,6,1.70,223.4,98,37.980000,220.6,101,18.75,203.9,118,9.18,0,no
7,121,yes,24,no,7.5,7,2.03,218.2,88,37.090000,348.5,108,29.62,212.6,118,9.57,3,no
8,147,no,0,yes,7.1,6,1.92,157.0,79,26.690000,103.1,94,8.76,211.8,96,9.53,0,no
9,117,no,0,no,8.7,4,2.35,184.5,97,31.370000,351.6,80,29.89,215.8,90,9.71,1,no
10,141,yes,37,yes,11.2,5,3.02,258.6,84,43.960000,222.0,111,18.87,326.4,97,14.69,0,no
11,65,no,0,no,12.7,6,3.43,129.1,137,21.950000,228.5,83,19.42,208.8,111,9.40,4,yes
12,74,no,0,no,9.1,5,2.46,187.7,127,31.910000,163.4,148,13.89,196.0,94,8.82,0,no
13,168,no,0,no,11.2,2,3.02,128.8,96,30.653501,104.9,71,8.92,141.1,128,6.35,1,no
14,95,no,0,no,12.3,5,3.32,156.6,88,26.620000,247.6,75,21.05,192.3,115,8.65,3,no
15,62,no,0,no,13.1,6,3.54,120.7,70,20.520000,307.2,76,26.11,203.0,99,9.14,4,no

In [11]:
# To Convert Categorical class column in to numeric 
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['voice.plan']=le.fit_transform(df['voice.plan'])
df['intl.plan']= le.fit_transform(df['intl.plan'])
df['churn']=le.fit_transform(df['churn'])

In [12]:
df.head()

,account.length,voice.plan,voice.messages,intl.plan,intl.mins,intl.calls,intl.charge,day.mins,day.calls,day.charge,eve.mins,eve.calls,eve.charge,night.mins,night.calls,night.charge,customer.calls,churn
1,128,1,25,0,10.0,3,2.70,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,1,0
2,107,1,26,0,13.7,3,3.70,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,1,0
3,137,0,0,0,12.2,5,3.29,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,0,0
4,84,0,0,1,6.6,7,1.78,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,2,0
5,75,0,0,1,10.1,3,2.73,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,3,0

In [13]:
df.dtypes

account.length      int64
voice.plan          int32
voice.messages      int64
intl.plan           int32
intl.mins         float64
intl.calls          int64
intl.charge       float64
day.mins          float64
day.calls           int64
day.charge        float64
eve.mins          float64
eve.calls           int64
eve.charge        float64
night.mins        float64
night.calls         int64
night.charge      float64
customer.calls      int64
churn               int32
dtype: object

In [14]:
# Changing Column Name 
df1 = df.rename(columns={'account.length':'account_length','voice.plan':'voice_plan','voice.messages':'voice_messages','intl.plan':'international_plan',
                  'intl.mins':'international_mins','intl.calls':'international_calls','intl.charge':'international_charge',
                  'day.mins':'day_mins','day.calls':'day_calls','day.charge':'day_charge','eve.mins':'evening_mins','eve.calls':'evening_calls',
                  'eve.charge':'evening_charge','night.mins':'night_mins','night.calls':'night_calls','night.charge':'night_charge','customer.calls':'customer_calls'})

In [15]:
df1.corr()

,account_length,voice_plan,voice_messages,international_plan,international_mins,international_calls,international_charge,day_mins,day_calls,day_charge,evening_mins,evening_calls,evening_charge,night_mins,night_calls,night_charge,customer_calls,churn
account_length,1.000000,-0.006650,-0.014575,0.014681,0.001291,0.014277,0.001292,-0.001017,0.028240,-0.000799,-0.008688,0.009143,-0.009587,0.000668,-0.007825,0.000656,-0.001445,0.021203
voice_plan,-0.006650,1.000000,0.954508,0.009054,0.004116,-0.007525,0.004165,0.002059,-0.001735,0.001805,0.022978,-0.005916,0.023332,0.005524,0.009176,0.005522,-0.014453,-0.110698
voice_messages,-0.014575,0.954508,1.000000,0.011947,0.002463,0.000124,0.002505,0.005381,0.000883,0.005138,0.018862,-0.003954,0.019496,0.005541,0.002676,0.005535,-0.007086,-0.097633
international_plan,0.014681,0.009054,0.011947,1.000000,0.031799,0.004493,0.031751,0.028138,0.008102,0.028012,0.019942,0.002505,0.021234,-0.026508,0.005623,-0.026510,-0.012974,0.259123
international_mins,0.001291,0.004116,0.002463,0.031799,1.000000,0.016791,0.999993,-0.019486,0.013097,-0.019281,-0.000346,-0.007458,0.000132,-0.006721,0.000391,-0.006717,-0.012122,0.063285
international_calls,0.014277,-0.007525,0.000124,0.004493,0.016791,1.000000,0.016900,-0.001303,0.010893,-0.001599,0.007987,0.005574,0.008393,-0.017214,-0.000156,-0.017182,-0.019147,-0.046893
international_charge,0.001292,0.004165,0.002505,0.031751,0.999993,0.016900,1.000000,-0.019415,0.013161,-0.019211,-0.000323,-0.007507,0.000155,-0.006655,0.000368,-0.006650,-0.012180,0.063275
day_mins,-0.001017,0.002059,0.005381,0.028138,-0.019486,-0.001303,-0.019415,1.000000,0.001935,0.999767,-0.010907,0.008128,-0.010760,0.011799,0.004236,0.011783,0.002733,0.207705
day_calls,0.028240,-0.001735,0.000883,0.008102,0.013097,0.010893,0.013161,0.001935,1.000000,0.001665,-0.001724,0.003754,-0.000695,0.002804,-0.008308,0.002802,-0.010739,0.016130
day_charge,-0.000799,0.001805,0.005138,0.028012,-0.019281,-0.001599,-0.019211,0.999767,0.001665,1.000000,-0.011534,0.007982,-0.011386,0.011315,0.004206,0.011299,0.002929,0.207578
evening_mins,-0.008688,0.022978,0.018862,0.019942,-0.000346,0.007987,-0.000323,-0.010907,-0.001724,-0.011534,1.000000,0.003110,0.997662,-0.016501,0.015590,-0.016503,-0.012394,0.089180
evening_calls,0.009143,-0.005916,-0.003954,0.002505,-0.007458,0.005574,-0.007507,0.008128,0.003754,0.007982,0.003110,1.000000,0.002778,0.001781,-0.013682,0.001799,0.006235,-0.006284
evening_charge,-0.009587,0.023332,0.019496,0.021234,0.000132,0.008393,0.000155,-0.010760,-0.000695,-0.011386,0.997662,0.002778,1.000000,-0.016649,0.013422,-0.016652,-0.013836,0.089282
night_mins,0.000668,0.005524,0.005541,-0.026508,-0.006721,-0.017214,-0.006655,0.011799,0.002804,0.011315,-0.016501,0.001781,-0.016649,1.000000,0.026972,0.999999,-0.008533,0.045677
night_calls,-0.007825,0.009176,0.002676,0.005623,0.000391,-0.000156,0.000368,0.004236,-0.008308,0.004206,0.015590,-0.013682,0.013422,0.026972,1.000000,0.026949,-0.008283,-0.006986
night_charge,0.000656,0.005522,0.005535,-0.026510,-0.006717,-0.017182,-0.006650,0.011783,0.002802,0.011299,-0.016503,0.001799,-0.016652,0.999999,0.026949,1.000000,-0.008530,0.045673
customer_calls,-0.001445,-0.014453,-0.007086,-0.012974,-0.012122,-0.019147,-0.012180,0.002733,-0.010739,0.002929,-0.012394,0.006235,-0.013836,-0.008533,-0.008283,-0.008530,1.000000,0.212564
churn,0.021203,-0.110698,-0.097633,0.259123,0.063285,-0.046893,0.063275,0.207705,0.016130,0.207578,0.089180,-0.006284,0.089282,0.045677,-0.006986,0.045673,0.212564,1.000000

In [16]:
# Outlier Treatment
# Considering columns whose outliers need to be treated
req_col = ['account_length','voice_messages','international_calls','day_mins', 'evening_mins', 'night_mins', 'international_mins', 'day_calls', 'day_charge', 'evening_calls', 
           'international_charge','evening_charge', 'night_calls', 'night_charge','customer_calls']

In [17]:
# Calculate quartile And IQR 
q1 = np.percentile(df1[req_col],25)
q3 = np.percentile(df1[req_col],75)
iqr = q3 - q1

# Get Lower and upper bound
upper = q3+1.5*iqr 
lower = q1-1.5*iqr

outlier = ((df1[req_col]<lower) | (df1[req_col]>upper))

# Get the indices of outlier rows
outlier_indices = np.where(outlier)[0]

print("Total No. of Outlier:",len(outlier_indices))
print("\n","Outlier Indices :",outlier_indices)

Total No. of Outlier: 711

 Outlier Indices : [   3    6    8    9   14   15   15   16   32   42   42   52   70   76
   80   85  106  117  149  151  155  156  179  180  194  197  198  201
  229  230  244  247  265  283  284  287  289  289  290  299  302  302
  303  307  315  320  330  337  360  363  365  378  383  386  389  415
  419  422  431  434  436  438  444  447  461  473  475  478  487  497
  507  507  516  529  534  535  552  556  559  561  568  571  575  579
  580  583  584  590  605  606  611  616  617  619  629  632  634  656
  660  661  679  688  698  711  726  731  732  759  763  782  784  790
  791  802  803  815  815  827  832  838  845  846  862  871  873  876
  878  881  882  901  911  913  913  914  914  916  917  918  922  932
  939  941  957  961  975  984  985  990 1006 1011 1014 1025 1026 1045
 1078 1081 1112 1113 1123 1161 1163 1165 1165 1182 1188 1192 1197 1202
 1238 1254 1255 1270 1275 1276 1282 1291 1298 1317 1334 1344 1350 1355
 1375 1376 1382 1387 1416 1428 1445 1449 1455 1471 1477 1479 1483 1486
 1490 1492 1498 1511 1514 1534 1557 1564 1570 1580 1583 1585 1601 1606
 1609 1610 1610 1614 1625 1633 1636 1643 1645 1645 1646 1652 1656 1666
 1671 1679 1695 1698 1701 1718 1725 1731 1734 1736 1738 1739 1774 1775
 1786 1794 1809 1818 1830 1837 1849 1856 1857 1872 1878 1888 1891 1897
 1899 1908 1915 1923 1924 1924 1932 1934 1934 1941 1971 1973 1980 1996
 2001 2028 2028 2034 2035 2071 2074 2080 2081 2089 2099 2103 2111 2113
 2129 2136 2139 2145 2149 2150 2154 2160 2162 2177 2183 2186 2188 2196
 2203 2213 2214 2215 2250 2259 2260 2261 2267 2270 2271 2280 2281 2289
 2305 2309 2311 2312 2321 2331 2336 2337 2344 2345 2356 2365 2376 2388
 2390 2395 2397 2400 2401 2406 2409 2412 2413 2435 2435 2437 2442 2458
 2468 2477 2478 2480 2483 2484 2490 2493 2503 2517 2525 2528 2536 2539
 2543 2549 2551 2567 2572 2573 2580 2594 2595 2600 2603 2605 2606 2609
 2614 2618 2620 2627 2629 2629 2637 2639 2640 2641 2647 2648 2660 2662
 2663 2666 2675 2677 2688 2696 2697 2708 2715 2715 2720 2721 2728 2732
 2747 2754 2757 2757 2766 2767 2780 2789 2791 2793 2801 2808 2822 2824
 2839 2858 2862 2868 2869 2874 2876 2884 2926 2926 2933 2936 2942 2947
 2985 2994 3000 3010 3019 3027 3040 3060 3061 3072 3075 3077 3083 3087
 3096 3100 3103 3107 3113 3127 3132 3133 3135 3146 3151 3152 3161 3163
 3168 3174 3197 3202 3205 3205 3207 3215 3219 3240 3254 3255 3257 3268
 3272 3273 3278 3288 3311 3318 3319 3322 3326 3330 3335 3335 3340 3355
 3360 3373 3376 3376 3381 3382 3395 3424 3440 3442 3443 3465 3477 3478
 3483 3486 3496 3502 3505 3514 3525 3537 3540 3547 3548 3551 3553 3563
 3565 3578 3587 3596 3602 3604 3608 3609 3613 3617 3623 3628 3636 3644
 3650 3654 3655 3656 3663 3667 3675 3681 3681 3686 3687 3688 3690 3697
 3700 3710 3733 3751 3756 3759 3763 3765 3767 3767 3769 3771 3777 3787
 3812 3822 3825 3830 3831 3834 3839 3840 3864 3871 3883 3884 3885 3886
 3892 3893 3899 3901 3905 3917 3920 3929 3931 3931 3949 3955 3955 3960
 3963 3966 3967 3983 3987 3993 3994 4021 4027 4051 4060 4079 4082 4088
 4090 4094 4095 4102 4111 4118 4121 4135 4140 4141 4157 4158 4161 4171
 4178 4185 4190 4190 4198 4205 4206 4217 4222 4224 4229 4232 4241 4258
 4265 4269 4271 4271 4279 4280 4288 4299 4306 4307 4307 4311 4318 4330
 4332 4347 4382 4396 4398 4403 4409 4417 4436 4441 4443 4467 4476 4476
 4491 4535 4537 4542 4544 4545 4547 4564 4569 4577 4602 4613 4614 4621
 4625 4625 4626 4631 4638 4649 4651 4658 4664 4665 4689 4706 4710 4715
 4726 4727 4730 4731 4737 4740 4764 4779 4782 4786 4793 4800 4809 4830
 4832 4834 4837 4839 4840 4849 4850 4862 4866 4892 4895 4897 4898 4899
 4914 4918 4919 4924 4924 4943 4947 4950 4959 4991 4995]

In [18]:
# Reset the index the dataframe
df_reset_index = df1.reset_index(drop=True)
# Remove row with outlier indices
df_clean = df_reset_index.drop(outlier_indices)
# print the modified dataframe
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4321 entries, 0 to 4999
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   account_length        4321 non-null   int64
 1   voice_plan            4321 non-null   int32
 2   voice_messages        4321 non-null   int64
 3   international_plan    4321 non-null   int32
 4   international_mins    4321 non-null   float64
 5   international_calls   4321 non-null   int64
 6   international_charge  4321 non-null   float64
 7   day_mins              4321 non-null   float64
 8   day_calls             4321 non-null   int64
 9   day_charge            4321 non-null   float64
 10  evening_mins          4321 non-null   float64
 11  evening_calls         4321 non-null   int64
 12  evening_charge        4321 non-null   float64
 13  night_mins            4321 non-null   float64
 14  night_calls           4321 non-null   int64
 15  night_charge          4321 non-null   float64
 16  customer_calls        4321 non-null   int64
 17  churn                 4321 non-null   int32
dtypes: float64(8), int32(3), int64(7)
memory usage: 590.8 KB

In [19]:
# Feature Selection- Using Univariate Analysis
data = df_clean.drop(['churn'],axis=1)

from sklearn.feature_selection import SelectKBest,f_classif
select = SelectKBest(f_classif,k=9)

data_req = select.fit_transform(data,df_clean['churn'])
data_req

array([[  1.  ,   0.  ,  10.  , ..., 197.4 ,  16.78,   1.  ],
       [  1.  ,   0.  ,  13.7 , ..., 195.5 ,  16.62,   1.  ],
       [  0.  ,   0.  ,  12.2 , ..., 121.2 ,  10.3 ,   0.  ],
       ...,
       [  0.  ,   0.  ,  13.6 , ..., 172.8 ,  14.69,   1.  ],
       [  0.  ,   0.  ,   8.5 , ..., 171.7 ,  14.59,   0.  ],
       [  1.  ,   0.  ,   9.3 , ..., 267.1 ,  22.7 ,   0.  ]])

In [20]:
df_new = pd.DataFrame(select.inverse_transform(data_req),index=df_clean.index,columns=data.columns)

req_columns = df_new.columns[df_new.var()!=0]
df_final = df_new[req_columns]

df_target = df_clean['churn']
Final_df = pd.concat([df_final, df_target], axis =1)

Final_df.describe()

,voice_plan,international_plan,international_mins,international_charge,day_mins,day_charge,evening_mins,evening_charge,customer_calls,churn
count,4321.000000,4321.000000,4321.000000,4321.000000,4321.000000,4321.000000,4321.000000,4321.000000,4321.000000,4321.000000
mean,0.266605,0.092571,10.270678,2.773585,176.338533,29.982540,194.601524,16.545832,1.579495,0.118954
std,0.442235,0.289864,2.758645,0.744738,50.098874,8.514469,45.060847,3.841554,1.313123,0.323772
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,8.500000,2.300000,142.300000,24.230000,164.300000,13.960000,1.000000,0.000000
50%,0.000000,0.000000,10.300000,2.780000,177.900000,30.260000,197.700000,16.790000,1.000000,0.000000
75%,1.000000,0.000000,12.000000,3.240000,212.900000,36.190000,227.200000,19.350000,2.000000,0.000000
max,1.000000,1.000000,20.000000,5.400000,280.400000,47.670000,280.800000,26.960000,9.000000,1.000000

# Balancing the Data

In [27]:
# Oversampling Minor Class
from imblearn.over_sampling import SMOTE

In [28]:
x = Final_df.iloc[:,:9]
y = Final_df['churn']
# Implementing Oversampling for Handling imbalanced
smk = SMOTE(sampling_strategy='minority',random_state=0)
x_res , y_res = smk.fit_resample(x ,y)
final_bal = pd.concat([pd.DataFrame(x_res),pd.DataFrame(y_res)],axis=1)
final_bal

,voice_plan,international_plan,international_mins,international_charge,day_mins,day_charge,evening_mins,evening_charge,customer_calls,churn
0,1.0,0.000000,10.000000,2.700000,265.100000,45.070000,197.400000,16.780000,1.000000,0
1,1.0,0.000000,13.700000,3.700000,161.600000,27.470000,195.500000,16.620000,1.000000,0
2,0.0,0.000000,12.200000,3.290000,243.400000,41.380000,121.200000,10.300000,0.000000,0
3,0.0,1.000000,10.100000,2.730000,166.700000,28.340000,148.300000,12.610000,3.000000,0
4,0.0,1.000000,6.300000,1.700000,223.400000,37.980000,220.600000,18.750000,0.000000,0
...,...,...,...,...,...,...,...,...,...,...
7609,0.0,0.486356,12.000000,3.240000,271.604975,46.172359,260.004492,22.101814,1.513644,1
7610,0.0,0.000000,12.932982,3.490905,135.803906,23.084575,240.778176,20.466683,5.000000,1
7611,0.0,0.000000,9.614719,2.593331,132.429439,22.513718,195.191428,16.590539,4.000000,1
7612,0.0,0.000000,11.953139,3.223637,103.937475,17.667980,214.010032,18.193903,4.000000,1
7613,0.0,0.000000,9.509825,2.572070,271.651580,46.179439,225.657193,19.184070,0.835088,1

In [29]:
print(final_bal['churn'].value_counts())

0    3807
1    3807
Name: churn, dtype: int64

## Build Model : Balanced Processed data post Feature Engineering

In [30]:
#Feature & Target Variables
X1 = final_bal.iloc[:, :9]
Y1 = final_bal['churn']

X1_train, X1_test, Y1_train, Y1_test = train_test_split(X1, Y1, test_size= 0.3, random_state=10)

In [31]:
rf = RandomForestClassifier(random_state=0,class_weight='balanced')
rf.fit(X1_train,Y1_train)
# Train model 
y_pred_rf_train = rf.predict(X1_train)
acc_rf_train = accuracy_score(y_pred_rf_train,Y1_train)
print('Training Accuracy:',acc_rf_train*100)
# Test Model
y_pred_rf_test = rf.predict(X1_test)
acc_rf_test = accuracy_score(y_pred_rf_test,Y1_test)
print('Testing Accuracy:',acc_rf_test*100)
print('\n')
print(classification_report(y_pred_rf_test,Y1_test))
print('\n')
print(confusion_matrix(Y1_test,y_pred_rf_test))

Training Accuracy: 100.0
Testing Accuracy: 95.49234135667396


              precision    recall  f1-score   support

           0       0.96      0.95      0.96      1186
           1       0.94      0.96      0.95      1099

    accuracy                           0.95      2285
   macro avg       0.95      0.96      0.95      2285
weighted avg       0.96      0.95      0.95      2285



[[1124   41]
 [  62 1058]]

In [32]:
import pickle
pickle_out = open("rf.pkl","wb")
pickle.dump(rf,pickle_out)
pickle_out.close()